### ISSUE TITLE
Patch for /trunk/whitepapers/central/box_obs_time_sas.yml

### ISSUE THREAD

**Issue by GoogleCodeExporter** [phuse-org/phuse-scripts#10]
```
removed comment
```

Original issue reported on code.google.com by `pdotscha...@gmail.com` on 16 Mar 2015 at 11:33

Attachments:
* [box_obs_time_sas.yml.patch](https://storage.googleapis.com/google-code-attachments/phuse-scripts/issue-10/comment-0/box_obs_time_sas.yml.patch)

**Comment by DanteDT** [comment]
clean-up after google code export. d
