### ISSUE TITLE
Patch for /trunk/whitepapers/outliers/hi_lo_abnorm_sas.yml

### ISSUE THREAD

**Issue by GoogleCodeExporter** [phuse-org/phuse-scripts#11]
```
Updated during Scriptathon
```

Original issue reported on code.google.com by `johnesal...@sky.com` on 16 Mar 2015 at 11:35

Attachments:
* [hi_lo_abnorm_sas.yml.patch](https://storage.googleapis.com/google-code-attachments/phuse-scripts/issue-11/comment-0/hi_lo_abnorm_sas.yml.patch)

**Comment by DanteDT** [comment]
clean-up after google code export. d
