### ISSUE TITLE
Patch for /trunk/whitepapers/demographics/demo_summary.R

### ISSUE THREAD

**Issue by GoogleCodeExporter** [phuse-org/phuse-scripts#6]
```
ensure required packages are installed at top
```

Original issue reported on code.google.com by `dant...@gmail.com` on 12 Dec 2014 at 3:39

Attachments:
* [demo_summary.R.patch](https://storage.googleapis.com/google-code-attachments/phuse-scripts/issue-6/comment-0/demo_summary.R.patch)

**Comment by DanteDT** [comment]
clean-up after google code export. d
