### ISSUE TITLE
Patch for /trunk/contributed/Demographics/Scripts/demographics_sas.yml

### ISSUE THREAD

**Issue by GoogleCodeExporter** [phuse-org/phuse-scripts#7]
```
updated per scriptathon
```

Original issue reported on code.google.com by `adrienne...@phuse.eu` on 16 Mar 2015 at 11:10

Attachments:
* [demographics_sas.yml.patch](https://storage.googleapis.com/google-code-attachments/phuse-scripts/issue-7/comment-0/demographics_sas.yml.patch)

**Comment by DanteDT** [comment]
clean-up after google code export. d
