### ISSUE TITLE
Patch for /trunk/whitepapers/central/box_obs_time_Rnw.yml

### ISSUE THREAD

**Issue by GoogleCodeExporter** [phuse-org/phuse-scripts#8]
```
changed Stage to Contributed, and added Figure 7.1 to Title
```

Original issue reported on code.google.com by `Gustav.B...@gmail.com` on 16 Mar 2015 at 11:17

Attachments:
* [box_obs_time_Rnw.yml.patch](https://storage.googleapis.com/google-code-attachments/phuse-scripts/issue-8/comment-0/box_obs_time_Rnw.yml.patch)

**Comment by DanteDT** [comment]
clean-up after google code export. d
