### ISSUE TITLE
Patch for /trunk/whitepapers/outliers/TE_Abnormal_Summary_sas.yml

### ISSUE THREAD

**Issue by GoogleCodeExporter** [phuse-org/phuse-scripts#9]
```
Updated Title to match what is in the White Paper
```

Original issue reported on code.google.com by `rebekaTa...@gmail.com` on 16 Mar 2015 at 11:26

Attachments:
* [TE_Abnormal_Summary_sas.yml.patch](https://storage.googleapis.com/google-code-attachments/phuse-scripts/issue-9/comment-0/TE_Abnormal_Summary_sas.yml.patch)

**Comment by DanteDT** [comment]
clean-up after google code export. d
